packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  dotenv-cli: ^10.0.0
  next: ^15.4.5
  superjson: ^2.2.2
  typescript: ^5.8.3
  zod: ^3.25.49
  "@types/node": ^20
  "@t3-oss/env-nextjs": ^0.13.8
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0

catalogs:
  prisma:
    "@prisma/client": ^6.13.0
    prisma: ^6.13.0

  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19
    "@types/react-dom": ^19
