packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@t3-oss/env-nextjs": ^0.13.8
  dotenv-cli: ^10.0.0
  next: ^15.3.3
  typescript: ^5.8.3
  zod: ^3.25.49

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5

