packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  date-fns: ^4.1.0
  dotenv-cli: ^10.0.0
  fumadocs-core: ^16.2.5
  fumadocs-mdx: ^14.1.0
  fumadocs-ui: ^16.2.5
  lucide-react: ^0.511.0
  motion: ^12.23.24
  next: ^16.0.10
  next-mdx-remote: ^5.0.0
  next-themes: ^0.4.6
  resend: ^4.0.0
  superjson: ^2.2.2
  typescript: ^5.8.3
  zod: ^3.25.49
  "@types/node": ^20
  "@t3-oss/env-nextjs": ^0.13.8
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0

catalogs:
  prisma:
    "@prisma/extension-accelerate": ^2.0.2
    "@prisma/client": ^6.18.0
    prisma: ^6.18.0

  react19:
    react: 19.2.1
    react-dom: 19.2.1
    "@types/react": ^19
    "@types/react-dom": ^19
